@URL=http://localhost:3000
@Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3MTc4NzU2MzEsImV4cCI6MTc0OTQxMTYzMSwiYXVkIjoiIiwic3ViIjoiIiwicm9sZSI6IkFkbWluIiwidXNlcklkIjoiMSJ9.wkkTCXXNSRj79juQyhZ8bMGoLHcANRyLKSa6YqM2gnE


###
GET {{URL}}/api/vendor
Authorization: Bearer {{Token}}


###
GET {{URL}}/api/vendor/2
Authorization: Bearer {{Token}}


###
POST {{URL}}/api/vendor
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "vendorCode": "string",
    "vendorName": "string",
    "vendorAddress": "string",
    "gstn": "string",
    "panCardNumber": "string",
    "contactPersonName": "string",
    "contactPersonNumber": "string",
    "paymentTerms": "string"
}


###
PUT {{URL}}/api/vendor/1
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "vendorCode": "updated",
    "vendorName": "updated",
    "vendorAddress": "updated",
    "gstn": "updated",
    "panCardNumber": "updated",
    "contactPersonName": "updated",
    "contactPersonNumber": "updated",
    "paymentTerms": "updated"
}


###
DELETE {{URL}}/api/vendor/2
Authorization: Bearer {{Token}}