@URL=http://localhost:5000
@Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3MTc4NzU2MzEsImV4cCI6MTc0OTQxMTYzMSwiYXVkIjoiIiwic3ViIjoiIiwicm9sZSI6IkFkbWluIiwidXNlcklkIjoiMSJ9.wkkTCXXNSRj79juQyhZ8bMGoLHcANRyLKSa6YqM2gnE


###
GET {{URL}}/api/vendor
Authorization: Bearer {{Token}}


###
GET {{URL}}/api/vendor/1
Authorization: Bearer {{Token}}


###
PUT {{URL}}/api/vendor/1
Content-Type: application/json
Authorization: Bearer {{Token}}

{
}


###
DELETE {{URL}}/api/vendor/1
Authorization: Bearer {{Token}}


